language: node_js

node_js:
  - "lts/*"
  - "8"
  - "7.6"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run bootstrap

script:
  - npm run lint
  - npm run test:coverage
